(define MAX '())
(define (find_max ls)
    (set! MAX (apply max ls))
)
(define (convert_ls func ls)
    (cond   ((empty? ls)
            	(begin
		            (display "max value: ")
		            (display MAX)
		            (display "\n")
		            (display "converted list: ")
		            (set! MAX ‘())
		            '()
            	)
            )
            ((empty? MAX)
                (begin  (func ls)
                        (if (= 0 (modulo MAX (car ls)))
                            (convert_ls func (cdr ls))
                            (cons (car ls) (convert_ls func (cdr ls)))
                        )
                )
            )
            (else
                (if (= 0 (modulo MAX (car ls)))
                    (convert_ls func (cdr ls))
                    (cons (car ls) (convert_ls func (cdr ls)))
                )
            )
    )
)